# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master, '**' ]
    tags:
      - "v0.[0-9]+.[0-9]+"
      - "v0.[0-9]+.[0-9]+.dev*"
  pull_request:
    branches: [ master ]

jobs:
  test-linux:
    #needs: test-sanity
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # FIXME Stick to 3.8.5 as 3.8.6 has broken `wait_for`
          - python: 3.8.5
            kafka: "2.4.0"
            scala: "2.12"
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsnappy-dev libkrb5-dev krb5-user

    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -m pip install -U "pip>=20.1"
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-py-${{ matrix.python }}-${{ hashFiles('requirements-ci.txt') }}-${{ hashFiles('setup.py') }}
        # If miss on key takes any other cache with different hashes, will download correct ones on next step anyway
        restore-keys: |
         ${{ runner.os }}-py-${{ matrix.python }}-

    - name: Install python dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-ci.txt
        pip install -vv -Ue .  # We set -vv to see compiler exceptions/warnings

    - name: Run All Tests
      run: |
        make ci-test-all
        mv coverage.xml coverage-ext.xml
      env:
        SCALA_VERSION: ${{ matrix.scala }}
        KAFKA_VERSION: ${{ matrix.kafka }}

    - name: Run All Tests without extensions
      run: |
        make ci-test-all
        mv coverage.xml coverage-py.xml
      env:
        AIOKAFKA_NO_EXTENSIONS: "1"
        SCALA_VERSION: ${{ matrix.scala }}
        KAFKA_VERSION: ${{ matrix.kafka }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage-ext.xml
        flags: integration,cext
        name: test-linux-${{ matrix.python }}-${{ matrix.kafka }}-${{ matrix.scala }}-ext
      if: ${{ always() }}

    - name: Upload coverage without cext to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage-py.xml
        flags: integration,purepy
        name: test-linux-${{ matrix.python }}-${{ matrix.kafka }}-${{ matrix.scala }}-py
      if: ${{ always() }}
      
      
  armv64_job:
    name: Build and Test for arm64
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          # FIXME Stick to 3.8.5 as 3.8.6 has broken `wait_for`
          - python: 3.8.5
            kafka: "2.4.0"
            scala: "2.12"
      fail-fast: false      
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Install and test aiokafka
      run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt update && \
              apt install -y python3.8 && \
              apt install -y python3.8-venv && \
              python3.8 -m venv .env && \
              source .env/bin/activate && \
              python -m pip install --upgrade pip && \
              apt-get update && \
              apt install -y build-essential && \
              apt-get install -y python3.8-dev && \
              apt-get install -y libsnappy-dev libkrb5-dev krb5-user && \
              python -m pip install -U "pip>=20.1" && \
              python -m pip install --upgrade pip setuptools wheel && \
              python -m pip install -r requirements-ci.txt && \
              python -m pip install -vv -Ue . && \
              make ci-test-all && \
              mv coverage.xml coverage-py.xml && \
              deactivate' 
